# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on: [push]

jobs:
  run_RL_test:

    name: test_building_training 
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout folder project
      uses: actions/checkout@v2
    - name: Build Docker image
      run: make build
    - name: Run tests in docker image
      run: make test